[phases.setup]
nixPkgs = ["php84", "php84Packages.composer", "nodejs_22"]

[phases.install]
cmds = ["composer install --optimize-autoloader --no-dev", "npm ci"]

[phases.build]
cmds = ["php artisan wayfinder:generate --with-form", "npm run build", "php artisan optimize"]

[start]
cmd = "php artisan serve --host=0.0.0.0 --port=$PORT"
